spring:
  application:
    name: application

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

camunda:
  bpm:
    admin-user:
      id: camunda
      password: camunda
      first-name: Camunda
    database:
      schema-update: true
      schema-name: s368530
      table-prefix: s368530.
    jpa:
      enabled: false
    filter:
      create: All tasks

---
spring:
  jackson:
    time-zone: UTC
  config:
    activate:
      on-profile: local


  datasource:
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
      unique-resource-name: application_database
      min-pool-size: 2
      max-pool-size: 10
      borrow-connection-timeout: 30
      max-idle-time: 60
      maintenance-interval: 60
      test-query: SELECT 1
      properties:
        user: s368530
        password: P7Woe7Cwyk2MjZnN
        serverName: localhost
        portNumber: 5436
        databaseName: studs
        currentSchema: s368530

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        transaction:
          coordinator_class: jta
        jta:
          platform: org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform

atomikos:
  properties:
    max-timeout: 300000
    default-jta-timeout: 30000
    log-base-dir: ./atomikos-log
    enable-logging: true

bank:
  base-url: http://localhost:1489
  callback-url: http://localhost:1488/api/payments/webhook

---
spring:
  jackson:
    time-zone: UTC
  config:
    activate:
      on-profile: helios


  datasource:
    xa:
      data-source-class-name: org.postgresql.xa.PGXADataSource
      unique-resource-name: application_database
      min-pool-size: 2
      max-pool-size: 10
      borrow-connection-timeout: 30
      max-idle-time: 60
      maintenance-interval: 60
      test-query: SELECT 1
      properties:
        user: s368530
        password: P7Woe7Cwyk2MjZnN
        serverName: pg
        portNumber: 5432
        databaseName: studs
        currentSchema: s368530

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        transaction:
          coordinator_class: jta
        jta:
          platform: org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform

atomikos:
  properties:
    max-timeout: 300000
    default-jta-timeout: 30000
    log-base-dir: ./atomikos-log
    enable-logging: true

bank:
  base-url: http://localhost:1489
  callback-url: http://localhost:1488/api/payments/webhook